In [1]:
import pandas as pd

from df.keiba_data_frame import KeibaDataFrame
from df.result_frame import ResultFrame
from env.reward import Reward

# Train Data 読み込み
# ※ 既に AI 側で filter/data 整備は実施済みのため再 type 明確化と、特定列を Drop のみ行っている。
kdf = KeibaDataFrame.from_data("./../data/train/2004_ranking_without_g.csv")
kdf.setting_types()

# Reward 準備
reward = Reward.initialize("./../data/train/2004_result.csv")

In [2]:
import numpy as np
from tensorflow import keras

new_model = keras.models.load_model("./../model/ranking_model_without_g")

preds = []

i = 0
for v in kdf.groups():
    v.reset_index(inplace=True, drop=True)
    obs = v.reindex(range(20), fill_value=-1).values.reshape(1, 1, 20, 51).tolist()
    q_values = new_model.predict(obs)
    print(q_values)
    action = np.argmax(q_values[0])
    pred_df = pd.DataFrame(
        {
            "track_id": v["track_id"],
            "date_num": v["date_num"],
            "round": v["round"],
            "number": v["number"],
            "pred": v["pred"],
            "action": action,
        }
    )
    preds.append(pred_df)
    i += 1
    if i > 10:
        break

preds_df = pd.concat(preds)

1/1 [==============================] - 0s 94ms/step
[[0. 0. 1. 0. 0. 0.]]
1/1 [==============================] - 0s 16ms/step
[[0. 0. 1. 0. 0. 0.]]
1/1 [==============================] - 0s 15ms/step
[[0. 0. 1. 0. 0. 0.]]
1/1 [==============================] - 0s 16ms/step
[[0. 0. 1. 0. 0. 0.]]
1/1 [==============================] - 0s 30ms/step
[[0. 0. 1. 0. 0. 0.]]
1/1 [==============================] - 0s 31ms/step
[[1. 0. 0. 0. 0. 0.]]
1/1 [==============================] - 0s 23ms/step
[[0. 0. 1. 0. 0. 0.]]
1/1 [==============================] - 0s 16ms/step
[[0. 0. 1. 0. 0. 0.]]
1/1 [==============================] - 0s 6ms/step
[[1. 0. 0. 0. 0. 0.]]
1/1 [==============================] - 0s 17ms/step
[[0. 0. 1. 0. 0. 0.]]
1/1 [==============================] - 0s 16ms/step
[[0. 0. 1. 0. 0. 0.]]


In [3]:
mikounyu_count = 0
kounyu_count = 0
atari_count = 0
hazure_count = 0
reward_total = 0

action_0_count = 0
action_1_count = 0
action_2_count = 0
action_3_count = 0
action_4_count = 0

df = preds_df.sort_values(
    ["date_num", "track_id", "round"], ascending=[True, True, True]
)

for _, v in df.groupby(["date_num", "track_id", "round"], sort=False):
    action = int(v.iloc[0]["action"])

    if action == 0:
        action_0_count += 1
    elif action == 1:
        action_1_count += 1
    elif action == 2:
        action_2_count += 1
    elif action == 3:
        action_3_count += 1
    elif action == 4:
        action_4_count += 1

    if action == 5:
        reward_total += 0
        mikounyu_count += 1
    else:
        kounyu_count += 1
        result = reward.calc(v, action)
        if result > 0:
            atari_count += 1
        else:
            hazure_count += 1

        reward_total += result

print(f"RANK_ONE_HORSE 回数: {action_0_count}")
print(f"RANK_TWO_HORSE 回数: {action_1_count}")
print(f"RANK_THREE_HORSE 回数: {action_2_count}")
print(f"RANK_FOUR_HORSE 回数: {action_3_count}")
print(f"RANK_FIVE_HORSE 回数: {action_4_count}")
print(f"未購入回数: {mikounyu_count}")
print(f"当たり馬券: {atari_count}")
print(f"はずれ馬券: {hazure_count}")
print(f"的中率: {(atari_count / (atari_count + hazure_count))}")
print(f"儲け: {reward_total}")

RANK_ONE_HORSE 回数: 2
RANK_TWO_HORSE 回数: 0
RANK_THREE_HORSE 回数: 9
RANK_FOUR_HORSE 回数: 0
RANK_FIVE_HORSE 回数: 0
未購入回数: 0
当たり馬券: 1
はずれ馬券: 10
的中率: 0.09090909090909091
儲け: -9500
